[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = [ "-w", "/settings/config.toml",]

[package]
name = "syrusakbary/cdn-starter-fb7"
version = "0.2.3"
description = "CDN Wasmer starter package"
readme = "README.md"
repository = "https://github.com/syrusakbary/cdn-starter-fb7"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "public"
"/settings" = "settings"
